### ISSUE TITLE
scan_topic issue

### ISSUE THREAD

**Issue by zoidzilla** [nkuwenjian/slam_karto_ceres#2]
Hi,

Your scan_topic in your launch file is not inserted as a variable in the slam_karto_ceres.cpp file.  On the contrary, you have it as a fixed topic and it is misleading. It took me some-time to realize that I cannot use a different name for a scan topic by changing your .launch file.

I hope it helps to correct your code.

Best regards!

**Comment by nkuwenjian** [comment]
Hi,

Thanks very much for your reminder. Currently, the remap tag is used to change the scan topic in the .launch file.

Best regards

Jian Wen
